### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by StefanSchroeder** [pyzahl/Gxsm3#1]
The sf repo has Tex sources that can be compiled into a manual.
They are missing in this repo. Will there be a separate repo or are they just hidden somewhere?

**Comment by toger5** [comment]
I also would be very happy about the most up to date documentation here on git. And also beeing able to easily submit PR's when adding more detail to the docs.

**Comment by StefanSchroeder** [comment]
I have now forked the original documentation from SVN into a new repo:
https://github.com/StefanSchroeder/Gxsm3-book

The PDF is built in a CI-CD-pipeline and available for the latest commits here (kept for 90 days):

https://github.com/StefanSchroeder/Gxsm3-book/actions

Please note that this is the documentation for Gxsm3; for Gxsm4 we are going to setup something new.
